# Generated by Django 4.2.3 on 2023-08-09 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 9, 16, 55, 16, 855898)),
        ),
    ]
